[2025-01-30T19:16:30.808+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-30T19:16:30.816+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.collect_raw_books manual__2025-01-30T12:13:05-07:00 [queued]>
[2025-01-30T19:16:30.821+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.collect_raw_books manual__2025-01-30T12:13:05-07:00 [queued]>
[2025-01-30T19:16:30.822+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-01-30T19:16:30.828+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): collect_raw_books> on 2025-01-30 19:13:05+00:00
[2025-01-30T19:16:30.830+0000] {standard_task_runner.py:72} INFO - Started process 330 to run task
[2025-01-30T19:16:30.832+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'collect_raw_books', 'manual__2025-01-30T12:13:05-07:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmp8_8cmue7']
[2025-01-30T19:16:30.833+0000] {standard_task_runner.py:105} INFO - Job 67: Subtask collect_raw_books
[2025-01-30T19:16:30.852+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag.collect_raw_books manual__2025-01-30T12:13:05-07:00 [running]> on host 48308722451a
[2025-01-30T19:16:30.888+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='collect_raw_books' AIRFLOW_CTX_EXECUTION_DATE='2025-01-30T19:13:05+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-30T12:13:05-07:00'
[2025-01-30T19:16:30.888+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-30T19:16:30.893+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-01-30T19:16:30.894+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/data_collection/collect_books.py --data_lake_path $DATA_LAKE_PATH --open_library_ids $OPEN_LIBRARY_IDS --execution_date $EXECUTION_DATE']
[2025-01-30T19:16:30.897+0000] {subprocess.py:99} INFO - Output:
[2025-01-30T19:16:40.190+0000] {subprocess.py:106} INFO - https://openlibrary.org/works/.json
[2025-01-30T19:16:40.191+0000] {subprocess.py:106} INFO - Error occurred in the request. It returned code: 404
[2025-01-30T19:16:40.191+0000] {subprocess.py:106} INFO -  {'error': 'notfound', 'key': '/works/'}
[2025-01-30T19:16:40.191+0000] {subprocess.py:106} INFO - /opt/***/data_lake/raw/json/20250130_book_
[2025-01-30T19:16:40.192+0000] {subprocess.py:106} INFO - https://openlibrary.org/works/"OL26974419M".json
[2025-01-30T19:16:40.192+0000] {subprocess.py:106} INFO - Error occurred in the request. It returned code: 404
[2025-01-30T19:16:40.192+0000] {subprocess.py:106} INFO -  {'error': 'notfound', 'key': '/works/"OL26974419M"'}
[2025-01-30T19:16:40.192+0000] {subprocess.py:106} INFO - /opt/***/data_lake/raw/json/20250130_book_"OL26974419M"
[2025-01-30T19:16:40.192+0000] {subprocess.py:106} INFO - https://openlibrary.org/works/"OL38631342M".json
[2025-01-30T19:16:40.193+0000] {subprocess.py:106} INFO - Error occurred in the request. It returned code: 404
[2025-01-30T19:16:40.193+0000] {subprocess.py:106} INFO -  {'error': 'notfound', 'key': '/works/"OL38631342M"'}
[2025-01-30T19:16:40.193+0000] {subprocess.py:106} INFO - /opt/***/data_lake/raw/json/20250130_book_"OL38631342M"
[2025-01-30T19:16:40.193+0000] {subprocess.py:106} INFO - https://openlibrary.org/works/"OL47317227M".json
[2025-01-30T19:16:40.193+0000] {subprocess.py:106} INFO - Error occurred in the request. It returned code: 404
[2025-01-30T19:16:40.193+0000] {subprocess.py:106} INFO -  {'error': 'notfound', 'key': '/works/"OL47317227M"'}
[2025-01-30T19:16:40.194+0000] {subprocess.py:106} INFO - /opt/***/data_lake/raw/json/20250130_book_"OL47317227M"
[2025-01-30T19:16:40.194+0000] {subprocess.py:106} INFO - https://openlibrary.org/works/"OL8759604M".json
[2025-01-30T19:16:40.194+0000] {subprocess.py:106} INFO - Error occurred in the request. It returned code: 404
[2025-01-30T19:16:40.194+0000] {subprocess.py:106} INFO -  {'error': 'notfound', 'key': '/works/"OL8759604M"'}
[2025-01-30T19:16:40.194+0000] {subprocess.py:106} INFO - /opt/***/data_lake/raw/json/20250130_book_"OL8759604M"
[2025-01-30T19:16:40.195+0000] {subprocess.py:106} INFO - https://openlibrary.org/works/"OL46057997M".json
[2025-01-30T19:16:40.195+0000] {subprocess.py:106} INFO - Error occurred in the request. It returned code: 404
[2025-01-30T19:16:40.195+0000] {subprocess.py:106} INFO -  {'error': 'notfound', 'key': '/works/"OL46057997M"'}
[2025-01-30T19:16:40.195+0000] {subprocess.py:106} INFO - /opt/***/data_lake/raw/json/20250130_book_"OL46057997M"
[2025-01-30T19:16:40.196+0000] {subprocess.py:106} INFO - https://openlibrary.org/works/"OL5204176M".json
[2025-01-30T19:16:40.196+0000] {subprocess.py:106} INFO - Error occurred in the request. It returned code: 404
[2025-01-30T19:16:40.196+0000] {subprocess.py:106} INFO -  {'error': 'notfound', 'key': '/works/"OL5204176M"'}
[2025-01-30T19:16:40.196+0000] {subprocess.py:106} INFO - /opt/***/data_lake/raw/json/20250130_book_"OL5204176M"
[2025-01-30T19:16:40.196+0000] {subprocess.py:106} INFO - https://openlibrary.org/works/"OL23338573M".json
[2025-01-30T19:16:40.196+0000] {subprocess.py:106} INFO - Error occurred in the request. It returned code: 404
[2025-01-30T19:16:40.197+0000] {subprocess.py:106} INFO -  {'error': 'notfound', 'key': '/works/"OL23338573M"'}
[2025-01-30T19:16:40.197+0000] {subprocess.py:106} INFO - /opt/***/data_lake/raw/json/20250130_book_"OL23338573M"
[2025-01-30T19:16:40.197+0000] {subprocess.py:106} INFO - https://openlibrary.org/works/"OL37985553M".json
[2025-01-30T19:16:40.197+0000] {subprocess.py:106} INFO - Error occurred in the request. It returned code: 404
[2025-01-30T19:16:40.197+0000] {subprocess.py:106} INFO -  {'error': 'notfound', 'key': '/works/"OL37985553M"'}
[2025-01-30T19:16:40.197+0000] {subprocess.py:106} INFO - /opt/***/data_lake/raw/json/20250130_book_"OL37985553M"
[2025-01-30T19:16:40.198+0000] {subprocess.py:106} INFO - https://openlibrary.org/works/"OL33899062M".json
[2025-01-30T19:16:40.198+0000] {subprocess.py:106} INFO - Error occurred in the request. It returned code: 404
[2025-01-30T19:16:40.198+0000] {subprocess.py:106} INFO -  {'error': 'notfound', 'key': '/works/"OL33899062M"'}
[2025-01-30T19:16:40.198+0000] {subprocess.py:106} INFO - /opt/***/data_lake/raw/json/20250130_book_"OL33899062M"
[2025-01-30T19:16:40.198+0000] {subprocess.py:106} INFO - https://openlibrary.org/works/"OL24503655M".json
[2025-01-30T19:16:40.198+0000] {subprocess.py:106} INFO - Error occurred in the request. It returned code: 404
[2025-01-30T19:16:40.198+0000] {subprocess.py:106} INFO -  {'error': 'notfound', 'key': '/works/"OL24503655M"'}
[2025-01-30T19:16:40.199+0000] {subprocess.py:106} INFO - /opt/***/data_lake/raw/json/20250130_book_"OL24503655M"
[2025-01-30T19:16:40.237+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-01-30T19:16:40.249+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-30T19:16:40.249+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=collect_raw_books, run_id=manual__2025-01-30T12:13:05-07:00, execution_date=20250130T191305, start_date=20250130T191630, end_date=20250130T191640
[2025-01-30T19:16:40.262+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-30T19:16:40.271+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-30T19:16:40.272+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
