[2025-02-03T19:06:58.210+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-03T19:06:58.219+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.collect_raw_books manual__2025-02-03T12:05:46-07:00 [queued]>
[2025-02-03T19:06:58.223+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.collect_raw_books manual__2025-02-03T12:05:46-07:00 [queued]>
[2025-02-03T19:06:58.224+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-03T19:06:58.232+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): collect_raw_books> on 2025-02-03 19:05:46+00:00
[2025-02-03T19:06:58.234+0000] {standard_task_runner.py:72} INFO - Started process 147 to run task
[2025-02-03T19:06:58.236+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'collect_raw_books', 'manual__2025-02-03T12:05:46-07:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dag.py', '--cfg-path', '/tmp/tmplncqj5sm']
[2025-02-03T19:06:58.237+0000] {standard_task_runner.py:105} INFO - Job 121: Subtask collect_raw_books
[2025-02-03T19:06:58.265+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag.collect_raw_books manual__2025-02-03T12:05:46-07:00 [running]> on host 48308722451a
[2025-02-03T19:06:58.312+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='collect_raw_books' AIRFLOW_CTX_EXECUTION_DATE='2025-02-03T19:05:46+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-03T12:05:46-07:00'
[2025-02-03T19:06:58.313+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-03T19:06:58.320+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-03T19:06:58.320+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 "/opt/***/data_collection/"collect_books.py --data_lake_path $DATA_LAKE_PATH --open_library_ids $OPEN_LIBRARY_IDS --execution_date $EXECUTION_DATE']
[2025-02-03T19:06:58.324+0000] {subprocess.py:99} INFO - Output:
[2025-02-03T19:07:43.855+0000] {subprocess.py:106} INFO - https://openlibrary.org/works/.json
[2025-02-03T19:07:43.862+0000] {subprocess.py:106} INFO - Error occurred in the request. It returned code: 404
[2025-02-03T19:07:43.863+0000] {subprocess.py:106} INFO -  {'error': 'notfound', 'key': '/works/'}
[2025-02-03T19:07:43.868+0000] {subprocess.py:106} INFO - /opt/***/data_lake/raw/json/books/20250203_book_
[2025-02-03T19:07:43.872+0000] {subprocess.py:106} INFO - https://openlibrary.org/works/OL38631342M.json
[2025-02-03T19:07:43.872+0000] {subprocess.py:106} INFO - /opt/***/data_lake/raw/json/books/20250203_book_OL38631342M
[2025-02-03T19:07:43.874+0000] {subprocess.py:106} INFO - https://openlibrary.org/works/OL5204176M.json
[2025-02-03T19:07:43.876+0000] {subprocess.py:106} INFO - /opt/***/data_lake/raw/json/books/20250203_book_OL5204176M
[2025-02-03T19:07:43.877+0000] {subprocess.py:106} INFO - https://openlibrary.org/works/[.json
[2025-02-03T19:07:43.879+0000] {subprocess.py:106} INFO - Error occurred in the request. It returned code: 404
[2025-02-03T19:07:43.880+0000] {subprocess.py:106} INFO -  {'error': 'notfound', 'key': '/works/['}
[2025-02-03T19:07:43.880+0000] {subprocess.py:106} INFO - /opt/***/data_lake/raw/json/books/20250203_book_[
[2025-02-03T19:07:43.881+0000] {subprocess.py:106} INFO - https://openlibrary.org/works/OL8759604M.json
[2025-02-03T19:07:43.881+0000] {subprocess.py:106} INFO - /opt/***/data_lake/raw/json/books/20250203_book_OL8759604M
[2025-02-03T19:07:43.881+0000] {subprocess.py:106} INFO - https://openlibrary.org/works/OL26974419M.json
[2025-02-03T19:07:43.882+0000] {subprocess.py:106} INFO - /opt/***/data_lake/raw/json/books/20250203_book_OL26974419M
[2025-02-03T19:07:43.882+0000] {subprocess.py:106} INFO - https://openlibrary.org/works/OL23338573M.json
[2025-02-03T19:07:43.882+0000] {subprocess.py:106} INFO - /opt/***/data_lake/raw/json/books/20250203_book_OL23338573M
[2025-02-03T19:07:43.883+0000] {subprocess.py:106} INFO - https://openlibrary.org/works/OL47317227M.json
[2025-02-03T19:07:43.883+0000] {subprocess.py:106} INFO - /opt/***/data_lake/raw/json/books/20250203_book_OL47317227M
[2025-02-03T19:07:43.883+0000] {subprocess.py:106} INFO - https://openlibrary.org/works/OL46057997M.json
[2025-02-03T19:07:43.884+0000] {subprocess.py:106} INFO - /opt/***/data_lake/raw/json/books/20250203_book_OL46057997M
[2025-02-03T19:07:43.884+0000] {subprocess.py:106} INFO - https://openlibrary.org/works/OL37985553M.json
[2025-02-03T19:07:43.884+0000] {subprocess.py:106} INFO - /opt/***/data_lake/raw/json/books/20250203_book_OL37985553M
[2025-02-03T19:07:43.885+0000] {subprocess.py:106} INFO - https://openlibrary.org/works/OL24503655M.json
[2025-02-03T19:07:43.885+0000] {subprocess.py:106} INFO - /opt/***/data_lake/raw/json/books/20250203_book_OL24503655M
[2025-02-03T19:07:43.885+0000] {subprocess.py:106} INFO - https://openlibrary.org/works/OL33899062M.json
[2025-02-03T19:07:43.886+0000] {subprocess.py:106} INFO - /opt/***/data_lake/raw/json/books/20250203_book_OL33899062M
[2025-02-03T19:07:43.886+0000] {subprocess.py:106} INFO - https://openlibrary.org/works/].json
[2025-02-03T19:07:43.886+0000] {subprocess.py:106} INFO - Error occurred in the request. It returned code: 404
[2025-02-03T19:07:43.887+0000] {subprocess.py:106} INFO -  {'error': 'notfound', 'key': '/works/]'}
[2025-02-03T19:07:43.887+0000] {subprocess.py:106} INFO - /opt/***/data_lake/raw/json/books/20250203_book_]
[2025-02-03T19:07:43.954+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-03T19:07:43.986+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-03T19:07:43.986+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=collect_raw_books, run_id=manual__2025-02-03T12:05:46-07:00, execution_date=20250203T190546, start_date=20250203T190658, end_date=20250203T190743
[2025-02-03T19:07:44.017+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-03T19:07:44.036+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-03T19:07:44.037+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
